<a href="https://colab.research.google.com/github/Mx095/ML_workshop/blob/main/ML_Assignment_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Perform arithmetic operations on NumPy arrays.

In [1]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
print("addition of array:",a+b)
print("subtraction of array:",a-b)
print("multiplication of array:",a*b)
print("division of array:",a/b)

addition of array: [5 7 9]
subtraction of array: [-3 -3 -3]
multiplication of array: [ 4 10 18]
division of array: [0.25 0.4  0.5 ]


2. Write a script to compute the mean and standard deviation of a NumPy array.


In [2]:
a=np.array([1,2,3,4,5])
print("mean of array: ",np.mean(a))
print("standard deviation of array: ",np.std(a))

mean of array:  3.0
standard deviation of array:  1.4142135623730951


3. Create a NumPy array of integers from 10 to 50 with a step size of 5.


In [3]:
a=np.arange(10,50,5)
print(a)

[10 15 20 25 30 35 40 45]


4. Reshape the array into a 2x4 matrix.

In [4]:
matrix=a.reshape(2,4)
print(matrix)

[[10 15 20 25]
 [30 35 40 45]]


5. Given the array arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]):
• Extract the sub-matrix containing the last two rows and first two columns.
• Replace all elements greater than 4 with 0.

In [5]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
sub_matrix=a[1:,:2]
print(sub_matrix)
a[a>4]=0
print(a)

[[4 5]
 [7 8]]
[[1 2 3]
 [4 0 0]
 [0 0 0]]


6. Create two 1D arrays:
• a = np.array([1, 2, 3])
• b = np.array([4, 5, 6])
• Perform element-wise addition, multiplication, and division

In [6]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print("addition of array:",a+b)
print("multiplication of array:",a*b)
print("division of array:",a/b)

addition of array: [5 7 9]
multiplication of array: [ 4 10 18]
division of array: [0.25 0.4  0.5 ]


7. Create a random NumPy array of size (4, 4). Compute:
• Mean of each column.
• Maximum value of the entire array.
• Sum of all elements.


In [7]:
a=np.random.rand(4,4)
print("mean of each column: ",np.mean(a,axis=0))
print("maximum value of the entire array: ",np.max(a))

mean of each column:  [0.61519538 0.56028012 0.59236587 0.58356864]
maximum value of the entire array:  0.9727450727781607


8. Given the array arr = np.array([1, 2, 3, 4]), add 10 to each element and multiply
the result by 2.

In [8]:
a= np.array([1, 2, 3, 4])
result = (a+ 10) * 2
print(result)

[22 24 26 28]


9. Perform advanced slicing and indexing on a 3D array.
Create a 3D NumPy array arr of shape (3, 4, 5) with random integers ranging from
1 to 100. Perform the following:
• Extract the second "layer" (i.e., the second 2D array) in the first dimension.
• Extract the first two rows and the last three columns from each "layer."
• Replace all elements divisible by 3 with -1

In [9]:
a=np.random.randint(1,101,size=(3,4,5))
print(a)
print("second layer",a[1])
print("first two rows and last three coloums",a[:,:2,-3:])
a[a%3==0]=-1
print(a)

[[[ 87  93  86  24   4]
  [ 37  37   6  12  41]
  [  2  53  18  75  64]
  [  5  29  58  44   3]]

 [[ 56   3  88  67  32]
  [ 22  13  24  74  48]
  [  9  82  94   4 100]
  [ 88  51  51  42  43]]

 [[ 77  75  92  60  84]
  [ 70  97  26  54  49]
  [ 82   5  92  61  31]
  [ 69  77  57  59  95]]]
second layer [[ 56   3  88  67  32]
 [ 22  13  24  74  48]
 [  9  82  94   4 100]
 [ 88  51  51  42  43]]
first two rows and last three coloums [[[86 24  4]
  [ 6 12 41]]

 [[88 67 32]
  [24 74 48]]

 [[92 60 84]
  [26 54 49]]]
[[[ -1  -1  86  -1   4]
  [ 37  37  -1  -1  41]
  [  2  53  -1  -1  64]
  [  5  29  58  44  -1]]

 [[ 56  -1  88  67  32]
  [ 22  13  -1  74  -1]
  [ -1  82  94   4 100]
  [ 88  -1  -1  -1  43]]

 [[ 77  -1  92  -1  -1]
  [ 70  97  26  -1  49]
  [ 82   5  92  61  31]
  [ -1  77  -1  59  95]]]


10. Work with broadcasting and advanced operations in NumPy.
 Create a NumPy array arr of shape (3, 3) with random integers between
 1 and 20. Perform the following:
• Subtract the mean of each row from its respective elements (row-wise
normalization).
• Create a new array by squaring all the elements in arr.
• Find the indices of the top 3 maximum values in the entire array

In [10]:
a=np.random.randint(1,21,size=(3,3))
print(a)
print("row-wise normalisation:",a-a.mean(axis=1,keepdims=True))
print("new array:",np.square(a))
print("top 3 maximum values:",np.argsort(a.flatten())[-3:])

[[ 1 18 17]
 [ 8  4  1]
 [18 20 13]]
row-wise normalisation: [[-11.           6.           5.        ]
 [  3.66666667  -0.33333333  -3.33333333]
 [  1.           3.          -4.        ]]
new array: [[  1 324 289]
 [ 64  16   1]
 [324 400 169]]
top 3 maximum values: [1 6 7]
